import hashlib
import importlib.util
import json
import os
import subprocess
import tempfile
import unittest
from pathlib import Path
from unittest import mock


ROOT = Path(__file__).resolve().parents[1]
SPEC = importlib.util.spec_from_file_location(
    "pohw_miner_registry_runtime_gate",
    ROOT / "scripts" / "pohw-miner-registry-runtime-gate.py",
)
MODULE = importlib.util.module_from_spec(SPEC)
assert SPEC.loader is not None
SPEC.loader.exec_module(MODULE)


class MinerRegistryRuntimeGateTests(unittest.TestCase):
    def test_raw_cid_matches_candidate_artifact(self):
        candidate = MODULE.load_lock(
            ROOT / "compatibility" / "experiment-1-miner-registry-candidate.json"
        )
        artifact = candidate["artifact"]
        self.assertEqual(MODULE.raw_cid(artifact["sha256"]), artifact["cid"])

    def test_candidate_is_bound_to_every_source_and_runtime_fixture(self):
        candidate_path = (
            ROOT / "compatibility" / "experiment-1-miner-registry-candidate.json"
        )
        candidate = MODULE.load_lock(candidate_path)
        contract = ROOT / candidate["artifact"]["path"]
        if not contract.exists():
            self.skipTest("registry WASM is generated by the AssemblyScript build")
        stack_lock = MODULE.load_lock(ROOT / "compatibility" / "stack-lock.json")
        verified, digest = MODULE.verify_candidate(
            ROOT, candidate_path, contract.resolve(), stack_lock
        )
        self.assertEqual(verified, candidate)
        self.assertEqual(digest, hashlib.sha256(candidate_path.read_bytes()).hexdigest())

    def test_launch_policy_binds_exact_candidate(self):
        launch = MODULE.load_lock(
            ROOT / "compatibility" / "experiment-1-launch-policy.json"
        )
        binding = launch["registry_source_candidate"]
        candidate_path = ROOT / binding["path"]
        self.assertEqual(
            binding["sha256"], hashlib.sha256(candidate_path.read_bytes()).hexdigest()
        )
        self.assertFalse(binding["deployment_authorized"])

    def test_duplicate_json_keys_fail_closed(self):
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "duplicate.json"
            path.write_text('{"schema":1,"schema":2}\n', encoding="utf-8")
            with self.assertRaisesRegex(MODULE.GateError, "duplicate object key"):
                MODULE.load_lock(path)

    def test_runtime_environment_drops_secrets_and_pins_toolchain(self):
        with tempfile.TemporaryDirectory() as temporary:
            with mock.patch.dict(
                os.environ,
                {"PATH": "/usr/bin", "IDENA_API_KEY": "must-not-cross-boundary"},
                clear=True,
            ):
                environment = MODULE.clean_environment(
                    Path(temporary), "/verified/module-cache", "1.26.5"
                )
        self.assertNotIn("IDENA_API_KEY", environment)
        self.assertEqual(environment["GOTOOLCHAIN"], "go1.26.5")
        self.assertEqual(environment["GOPROXY"], "off")

    def test_candidate_binds_exact_idena_go_commit(self):
        candidate = MODULE.load_lock(
            ROOT / "compatibility" / "experiment-1-miner-registry-candidate.json"
        )
        stack_lock = MODULE.load_lock(ROOT / "compatibility" / "stack-lock.json")
        locked = MODULE.locked_component(stack_lock, "idena-go")["commit"]
        self.assertEqual(candidate["runtime_binding"]["idena_go_commit"], locked)

    def test_exact_checkout_rejects_dirty_idena_go_tree(self):
        with tempfile.TemporaryDirectory() as temporary:
            worktree = Path(temporary)
            subprocess.run(["git", "init", "-q"], cwd=worktree, check=True)
            subprocess.run(
                ["git", "config", "user.email", "runtime-gate@example.invalid"],
                cwd=worktree,
                check=True,
            )
            subprocess.run(
                ["git", "config", "user.name", "Runtime Gate Test"],
                cwd=worktree,
                check=True,
            )
            tracked = worktree / "go.mod"
            tracked.write_text("module example.invalid/idena-go\n", encoding="utf-8")
            subprocess.run(["git", "add", "go.mod"], cwd=worktree, check=True)
            subprocess.run(["git", "commit", "-q", "-m", "fixture"], cwd=worktree, check=True)
            commit = subprocess.run(
                ["git", "rev-parse", "HEAD"],
                cwd=worktree,
                check=True,
                capture_output=True,
                text=True,
            ).stdout.strip()

            self.assertEqual(MODULE.verify_exact_clean_checkout(worktree, commit), commit)
            tracked.write_text("module example.invalid/modified\n", encoding="utf-8")
            with self.assertRaisesRegex(MODULE.GateError, "checkout is dirty"):
                MODULE.verify_exact_clean_checkout(worktree, commit)


if __name__ == "__main__":
    unittest.main()
