import hashlib
import importlib.util
import json
import os
import tempfile
import unittest
from pathlib import Path
from unittest import mock


ROOT = Path(__file__).resolve().parents[1]
SPEC = importlib.util.spec_from_file_location(
    "pohw_miner_registry_runtime_gate",
    ROOT / "scripts" / "pohw-miner-registry-runtime-gate.py",
)
MODULE = importlib.util.module_from_spec(SPEC)
assert SPEC.loader is not None
SPEC.loader.exec_module(MODULE)


class MinerRegistryRuntimeGateTests(unittest.TestCase):
    def test_raw_cid_matches_candidate_artifact(self):
        candidate = MODULE.load_lock(
            ROOT / "compatibility" / "experiment-1-miner-registry-candidate.json"
        )
        artifact = candidate["artifact"]
        self.assertEqual(MODULE.raw_cid(artifact["sha256"]), artifact["cid"])

    def test_candidate_is_bound_to_every_source_and_runtime_fixture(self):
        candidate_path = (
            ROOT / "compatibility" / "experiment-1-miner-registry-candidate.json"
        )
        candidate = MODULE.load_lock(candidate_path)
        contract = ROOT / candidate["artifact"]["path"]
        if not contract.exists():
            self.skipTest("registry WASM is generated by the AssemblyScript build")
        stack_lock = MODULE.load_lock(ROOT / "compatibility" / "stack-lock.json")
        verified, digest = MODULE.verify_candidate(
            ROOT, candidate_path, contract.resolve(), stack_lock
        )
        self.assertEqual(verified, candidate)
        self.assertEqual(digest, hashlib.sha256(candidate_path.read_bytes()).hexdigest())

    def test_launch_policy_binds_exact_candidate(self):
        launch = MODULE.load_lock(
            ROOT / "compatibility" / "experiment-1-launch-policy.json"
        )
        binding = launch["registry_source_candidate"]
        candidate_path = ROOT / binding["path"]
        self.assertEqual(
            binding["sha256"], hashlib.sha256(candidate_path.read_bytes()).hexdigest()
        )
        self.assertFalse(binding["deployment_authorized"])

    def test_duplicate_json_keys_fail_closed(self):
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "duplicate.json"
            path.write_text('{"schema":1,"schema":2}\n', encoding="utf-8")
            with self.assertRaisesRegex(MODULE.GateError, "duplicate object key"):
                MODULE.load_lock(path)

    def test_runtime_environment_drops_secrets_and_pins_toolchain(self):
        with tempfile.TemporaryDirectory() as temporary:
            with mock.patch.dict(
                os.environ,
                {"PATH": "/usr/bin", "IDENA_API_KEY": "must-not-cross-boundary"},
                clear=True,
            ):
                environment = MODULE.clean_environment(
                    Path(temporary), "/verified/module-cache", "1.26.5"
                )
        self.assertNotIn("IDENA_API_KEY", environment)
        self.assertEqual(environment["GOTOOLCHAIN"], "go1.26.5")
        self.assertEqual(environment["GOPROXY"], "off")


if __name__ == "__main__":
    unittest.main()
