import importlib.util
import os
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SPEC = importlib.util.spec_from_file_location(
    "pohw_governance_runtime_gate",
    ROOT / "scripts" / "pohw-governance-runtime-gate.py",
)
MODULE = importlib.util.module_from_spec(SPEC)
assert SPEC.loader is not None
SPEC.loader.exec_module(MODULE)


class GovernanceRuntimeGateTests(unittest.TestCase):
    def test_raw_cid_matches_locked_contract_artifact(self):
        digest = "8d05fd842aefd3d4a078038c8fbf8744af8a22d88b1fc7a56be27f7fe835da49"
        self.assertEqual(
            MODULE.raw_cid(digest),
            "bafkreienax6yikxp2pkka6adrsh37b2ev6fcfweld7d2k27cp576qno2je",
        )

    def test_duplicate_lock_keys_fail_closed(self):
        with tempfile.TemporaryDirectory() as temporary:
            lock = Path(temporary) / "lock.json"
            lock.write_text('{"schema":1,"schema":2}\n', encoding="utf-8")
            with self.assertRaisesRegex(MODULE.GateError, "duplicate object key"):
                MODULE.load_json(lock)

    def test_uncommitted_prototype_cannot_pass_locked_source_gate(self):
        lock = {
            "governancePrototype": {
                "sourceStatus": "uncommitted-local-prototype",
                "baseCommit": "0" * 40,
            },
            "components": [],
        }
        with self.assertRaisesRegex(MODULE.GateError, "uncommitted local prototype"):
            MODULE.verify_locked_sources(ROOT, lock, ROOT, {})

    @unittest.skipUnless(hasattr(os, "symlink"), "symlinks are unavailable")
    def test_symlinked_contract_artifact_is_rejected(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            target = root / "contract.wasm"
            target.write_bytes(b"fixture")
            link = root / "linked.wasm"
            os.symlink(target, link)
            with self.assertRaisesRegex(MODULE.GateError, "non-symlink"):
                MODULE.hash_regular_file(link)

    def test_repository_lock_is_valid_json(self):
        lock = MODULE.load_json(ROOT / "compatibility" / "governance-fork-lock.json")
        artifact = lock["governancePrototype"]["contractArtifact"]
        self.assertEqual(set(artifact), {"name", "size", "cid", "sha256"})
        self.assertRegex(artifact["sha256"], r"^[0-9a-f]{64}$")
        self.assertGreater(artifact["size"], 0)
        self.assertEqual(MODULE.raw_cid(artifact["sha256"]), artifact["cid"])

    def test_built_contract_matches_repository_lock(self):
        lock = MODULE.load_json(ROOT / "compatibility" / "governance-fork-lock.json")
        artifact = lock["governancePrototype"]["contractArtifact"]
        contract = ROOT / "contracts" / "idena-code-governance" / "build" / artifact["name"]
        if not contract.exists():
            self.skipTest("governance contract artifact is generated by the JavaScript build job")
        digest, size, cid = MODULE.verify_contract_artifact(contract, lock)
        self.assertEqual(digest, artifact["sha256"])
        self.assertEqual(size, artifact["size"])
        self.assertEqual(cid, artifact["cid"])


if __name__ == "__main__":
    unittest.main()
