[Unit]
RequiresMountsFor=/mnt/bitcoin-wd

[Service]
WorkingDirectory=/mnt/bitcoin-wd/bitcoin/bitcoin-core-mainnet
ExecStartPre=
ExecStartPre=/usr/bin/test -d /mnt/bitcoin-wd/bitcoin/bitcoin-core-mainnet
ExecStart=
ExecStart=/usr/local/bin/bitcoind -datadir=/mnt/bitcoin-wd/bitcoin/bitcoin-core-mainnet -disablewallet=1 -daemon=0
ReadWritePaths=
ReadWritePaths=/mnt/bitcoin-wd/bitcoin/bitcoin-core-mainnet
