[Service]
Group=ubuntu
ExecStart=
ExecStart=/home/ubuntu/idena-src/idena-node --config=/mnt/ssd/idena/idena-data/config.json --datadir=/mnt/ssd/idena/idena-data --fast=false
NoNewPrivileges=true
PrivateTmp=true
PrivateDevices=true
ProtectHome=read-only
ProtectSystem=strict
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
ProtectClock=true
ProtectHostname=true
RestrictSUIDSGID=true
RestrictNamespaces=true
LockPersonality=true
RestrictRealtime=true
SystemCallArchitectures=native
CapabilityBoundingSet=
AmbientCapabilities=
RestrictAddressFamilies=AF_INET AF_INET6 AF_NETLINK AF_UNIX
UMask=0077
ReadWritePaths=
ReadWritePaths=/mnt/ssd/idena/idena-data
ReadOnlyPaths=/home/ubuntu/idena-src
