[Unit]
RequiresMountsFor=
RequiresMountsFor=/var/lib/idena

[Service]
ExecStart=
ExecStart=/usr/local/libexec/idena-node-modern --config=/var/lib/idena/config.json --datadir=/var/lib/idena --fast=false
ReadWritePaths=
ReadWritePaths=/var/lib/idena
ReadOnlyPaths=
ReadOnlyPaths=/usr/local/libexec/idena-node-modern /var/lib/idena/config.json
