[Unit]
RequiresMountsFor=
RequiresMountsFor=/srv/sharechain

[Service]
User=pohw
Group=pohw
WorkingDirectory=/opt/p2pool
Environment=POHW_P2POOL_NODE_BIN=/usr/local/libexec/p2pool-experiment-1/p2pool-node
Environment=POHW_HEALTH_SCRIPT=/usr/local/libexec/p2pool-experiment-1/pohw-health-status.py
ExecStart=
ExecStart=/usr/local/libexec/p2pool-experiment-1/pohw-run-mining-adapter.sh
ReadOnlyPaths=
ReadOnlyPaths=/opt/p2pool /etc/pohw /usr/local/libexec/p2pool-experiment-1
ReadWritePaths=
ReadWritePaths=/srv/sharechain
