[Unit]
Requires=bitcoind-pohw-experiment-1.service
After=bitcoind-pohw-experiment-1.service
ConditionPathExists=
ConditionPathExists=/etc/pohw/enable-experiment-1-mining

[Service]
SupplementaryGroups=bitcoin-pohw-rpc
