[Unit]
Wants=network-online.target pohw-fork-chain-node.service
After=network-online.target pohw-fork-chain-node.service
RequiresMountsFor=
RequiresMountsFor=/srv/sharechain

[Service]
User=pohw
Group=pohw
WorkingDirectory=/opt/p2pool
ExecStart=
ExecStart=/opt/p2pool/scripts/pohw-run-gossip-mesh.sh
ReadOnlyPaths=
ReadOnlyPaths=/opt/p2pool /etc/pohw
ReadWritePaths=
ReadWritePaths=/srv/sharechain
