PubkeyAuthentication yes
PasswordAuthentication no
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
PermitRootLogin no
PermitEmptyPasswords no
AllowUsers ubuntu
MaxAuthTries 3
LoginGraceTime 30
X11Forwarding no
AllowTcpForwarding local
GatewayPorts no
PermitTunnel no
ClientAliveInterval 300
ClientAliveCountMax 2
